site_name: WidgetBot.io

# Repository
repo_name: 'widgetbot-io/embed'
repo_url: 'https://github.com/widgetbot-io/embed'
edit_uri: 'https://github.com/widgetbot-io/documentation/edit/master/docs/'

# Meta
site_description: 'Discord chat widgets for your website.'
site_author: 'WidgetBot'
copyright: 'Copyright &copy; 2018 Sam Denty'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.ico'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  feature:
    tabs: true

# Pages
pages:
  - Welcome: index.md
  - Tutorial: tutorial/index.md
  - Embed:
    - Getting started: embed/index.md
    - crate:
      - Intro: embed/crate/index.md
      - Options: embed/crate/options/index.md
      - API: embed/crate/api.md
      - Examples: embed/crate/examples/index.md
    - html-embed:
      - Intro: embed/html-embed/index.md
      - Attributes: embed/html-embed/attributes.md
      - API: embed/html-embed/api.md
    - react-embed:
      - Intro: embed/react-embed/index.md
      - Props: embed/react-embed/props.md
  - Self hosted:
      - Getting started: self-hosted/index.md
      - Configuration: self-hosted/config.md

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs
  - meta
  - footnotes
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# Resources
extra_javascript:
  - 'assets/js/crate.js'
extra_css:
  - 'assets/css/main.css'
  - 'assets/css/dark.css'

# Analytics
# google_analytics:
#   - 'UA-85426772-6'
#   - 'auto'

# Footer links
extra:
  social:
    - type: 'github'
      link: 'https://github.com/widgetbot-io'
    - type: 'twitter'
      link: 'https://twitter.com/widgetbot'
